const widgets = [
  { id: 'random', name: 'Random Discovery', icon: '🎲', desc: 'Khám phá ngẫu nhiên Wikipedia, facts, YouTube', badge: 'NEW' },
  { id: 'dice', name: 'Xúc xắc', icon: '🎲', desc: 'Tung xúc xắc 4, 6, 8, 12, 20 mặt' },
  { id: 'coin', name: 'Tung đồng xu', icon: '🪙', desc: 'Random heads or tails' },
  { id: 'number', name: 'Số ngẫu nhiên', icon: '🔢', desc: 'Sinh số trong khoảng' },
  { id: 'password', name: 'Mật khẩu', icon: '🔑', desc: 'Sinh mật khẩu mạnh' },
  { id: 'palette', name: 'Bảng màu', icon: '🎨', desc: 'Random color palettes' },
  { id: 'gradient', name: 'Gradient', icon: '🌈', desc: 'CSS gradient generator' },
  { id: 'activity', name: 'Gợi ý hoạt động', icon: '💡', desc: 'Gợi ý việc làm khi chán' },
  { id: '8ball', name: 'Magic 8-Ball', icon: '🔮', desc: 'Hỏi 8-Ball một câu' },
  { id: 'braindump', name: 'Brain Dump', icon: '🧠', desc: 'Sticky notes canvas' },
  { id: 'games', name: 'Mini Games', icon: '🎮', desc: 'Dice, coin, numbers' },
  { id: 'food', name: 'Ăn gì?', icon: '🍜', desc: 'Random món ăn cho bữa hôm nay' },
  { id: 'bmi', name: 'BMI Calculator', icon: '⚖️', desc: 'Tính chỉ số BMI' },
  { id: 'calendar', name: 'Lịch tháng', icon: '📅', desc: 'Xem lịch tháng này' },
  { id: 'cards', name: 'Rút bài', icon: '🃏', desc: 'Rút bài Tây ngẫu nhiên' },
  { id: 'challenge', name: 'Challenge', icon: '🏆', desc: 'Thử thách ngẫu nhiên' },
  { id: 'convert', name: 'Đổi đơn vị', icon: '📐', desc: 'Chuyển đổi độ dài, nhiệt độ' },
  { id: 'countdown', name: 'Đếm ngược', icon: '⏰', desc: 'Đếm ngược tới ngày chọn' },
  { id: 'counter', name: 'Counter', icon: '🔢', desc: 'Bộ đếm với bước nhảy' },
  { id: 'emoji', name: 'Emoji Mix', icon: '😎', desc: 'Trộn emoji ngẫu nhiên' },
  { id: 'guess', name: 'Đoán số', icon: '🎯', desc: 'Đoán số từ 1-100' },
  { id: 'history', name: 'Today in History', icon: '📜', desc: 'Sự kiện lịch sử hôm nay' },
  { id: 'idea', name: 'Idea Generator', icon: '💡', desc: 'Random ý tưởng dự án' },
  { id: 'list', name: 'Random List', icon: '📋', desc: 'Chọn ngẫu nhiên từ danh sách' },
  { id: 'mood', name: 'Mood Tracker', icon: '😊', desc: 'Ghi lại tâm trạng mỗi ngày (localStorage)' },
  { id: 'pomodoro', name: 'Pomodoro', icon: '🍅', desc: 'Timer 25-5-15 phút' },
  { id: 'rps', name: 'Oẳn tù tì', icon: '✊', desc: 'Kéo búa bao với máy' },
  { id: 'tarot', name: 'Tarot', icon: '🔮', desc: 'Rút bài tarot' },
  { id: 'textgen', name: 'Text Generator', icon: '📝', desc: 'Sinh văn bản mẫu' },
  { id: 'van', name: 'Random Văn', icon: '📖', desc: 'Ngẫu nhiên câu văn hay' },
  { id: 'workout', name: 'Workout', icon: '💪', desc: 'Random bài tập' },
];

export default widgets;
